/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.udistrital.cine.presentacion;

import javax.swing.JRadioButton;

/**
 *
 * @author USER
 */
public class VistaSillas extends javax.swing.JFrame {
 private JRadioButton [] SillasPreferenciales;
 private JRadioButton [] SillasGenerales;
 
    /**
     * Creates new form VistaSillas
     */
    public VistaSillas() {
        SillasGenerales = new JRadioButton[40];
        SillasPreferenciales = new JRadioButton[20];
        agregarJRBSillas();
        initComponents();
    }
    private void agregarJRBSillas (){
        SillasGenerales[0]=jRB1;
        SillasGenerales[1]=jRB2;
        SillasGenerales[2]=jRB3;
        SillasGenerales[3]=jRB4;
        SillasGenerales[4]=jRB5;
        SillasGenerales[5]=jRB6;
        SillasGenerales[6]=jRB7;
        SillasGenerales[7]=jRB8;
        SillasGenerales[8]=jRB9;
        SillasGenerales[9]=jRB10;
        SillasGenerales[10]=jRB11;
        SillasGenerales[11]=jRB12;
        SillasGenerales[12]=jRB13;
        SillasGenerales[13]=jRB14;
        SillasGenerales[14]=jRB15;
        SillasGenerales[15]=jRB16;
        SillasGenerales[16]=jRB17;
        SillasGenerales[17]=jRB18;
        SillasGenerales[18]=jRB19;
        SillasGenerales[19]=jRB20;
        SillasGenerales[20]=jRB21;
        SillasGenerales[21]=jRB22;
        SillasGenerales[22]=jRB23;
        SillasGenerales[23]=jRB24;
        SillasGenerales[24]=jRB25;
        SillasGenerales[25]=jRB26;
        SillasGenerales[26]=jRB27;
        SillasGenerales[27]=jRB28;
        SillasGenerales[28]=jRB29;
        SillasGenerales[29]=jRB30;
        SillasGenerales[30]=jRB31;
        SillasGenerales[31]=jRB32;
        SillasGenerales[32]=jRB33;
        SillasGenerales[33]=jRB34;
        SillasGenerales[34]=jRB35;
        SillasGenerales[35]=jRB36;
        SillasGenerales[36]=jRB37;
        SillasGenerales[37]=jRB38;
        SillasGenerales[38]=jRB39;
        SillasGenerales[39]=jRB40;
        SillasPreferenciales[0]=jRB41;
        SillasPreferenciales[1]=jRB42;
        SillasPreferenciales[2]=jRB43;
        SillasPreferenciales[3]=jRB44;
        SillasPreferenciales[4]=jRB45;
        SillasPreferenciales[5]=jRB46;
        SillasPreferenciales[6]=jRB47;
        SillasPreferenciales[7]=jRB48;
        SillasPreferenciales[8]=jRB49;
        SillasPreferenciales[9]=jRB50;
        SillasPreferenciales[10]=jRB51;
        SillasPreferenciales[11]=jRB52;
        SillasPreferenciales[12]=jRB53;
        SillasPreferenciales[13]=jRB54;
        SillasPreferenciales[14]=jRB55;
        SillasPreferenciales[15]=jRB56;
        SillasPreferenciales[16]=jRB57;
        SillasPreferenciales[17]=jRB58;
        SillasPreferenciales[18]=jRB59;
        SillasPreferenciales[19]=jRB60;
    }
    private void agregarEventos() {
        Controlador l = Controlador.GetInstance();
        for (JRadioButton SillaP: SillasPreferenciales) {
            SillaP.addActionListener(l);
        }
        for (JRadioButton SillaG: SillasGenerales) {
            SillaG.addActionListener(l);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton61 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jRB20 = new javax.swing.JRadioButton();
        jRB31 = new javax.swing.JRadioButton();
        jRB27 = new javax.swing.JRadioButton();
        jRB25 = new javax.swing.JRadioButton();
        jRB9 = new javax.swing.JRadioButton();
        jRB39 = new javax.swing.JRadioButton();
        jRB23 = new javax.swing.JRadioButton();
        jRB21 = new javax.swing.JRadioButton();
        jRB5 = new javax.swing.JRadioButton();
        jRB40 = new javax.swing.JRadioButton();
        jRB19 = new javax.swing.JRadioButton();
        jRB16 = new javax.swing.JRadioButton();
        jRB37 = new javax.swing.JRadioButton();
        jRB38 = new javax.swing.JRadioButton();
        jRB6 = new javax.swing.JRadioButton();
        jRB15 = new javax.swing.JRadioButton();
        jRB18 = new javax.swing.JRadioButton();
        jRB8 = new javax.swing.JRadioButton();
        jRB36 = new javax.swing.JRadioButton();
        jRB32 = new javax.swing.JRadioButton();
        jRB22 = new javax.swing.JRadioButton();
        jRB26 = new javax.swing.JRadioButton();
        jRB28 = new javax.swing.JRadioButton();
        jRB13 = new javax.swing.JRadioButton();
        jRB35 = new javax.swing.JRadioButton();
        jRB17 = new javax.swing.JRadioButton();
        jRB29 = new javax.swing.JRadioButton();
        jRB3 = new javax.swing.JRadioButton();
        jRB4 = new javax.swing.JRadioButton();
        jRB1 = new javax.swing.JRadioButton();
        jRB33 = new javax.swing.JRadioButton();
        jRB2 = new javax.swing.JRadioButton();
        jRB34 = new javax.swing.JRadioButton();
        jRB30 = new javax.swing.JRadioButton();
        jRB7 = new javax.swing.JRadioButton();
        jRB10 = new javax.swing.JRadioButton();
        jRB14 = new javax.swing.JRadioButton();
        jRB12 = new javax.swing.JRadioButton();
        jRB11 = new javax.swing.JRadioButton();
        jRB24 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRB41 = new javax.swing.JRadioButton();
        jRB42 = new javax.swing.JRadioButton();
        jRB43 = new javax.swing.JRadioButton();
        jRB44 = new javax.swing.JRadioButton();
        jRB45 = new javax.swing.JRadioButton();
        jRB46 = new javax.swing.JRadioButton();
        jRB47 = new javax.swing.JRadioButton();
        jRB48 = new javax.swing.JRadioButton();
        jRB49 = new javax.swing.JRadioButton();
        jRB50 = new javax.swing.JRadioButton();
        jRB51 = new javax.swing.JRadioButton();
        jRB52 = new javax.swing.JRadioButton();
        jRB53 = new javax.swing.JRadioButton();
        jRB54 = new javax.swing.JRadioButton();
        jRB55 = new javax.swing.JRadioButton();
        jRB56 = new javax.swing.JRadioButton();
        jRB57 = new javax.swing.JRadioButton();
        jRB58 = new javax.swing.JRadioButton();
        jRB59 = new javax.swing.JRadioButton();
        jRB60 = new javax.swing.JRadioButton();

        jRadioButton6.setText("jRadioButton1");

        jRadioButton13.setText("jRadioButton1");

        jRadioButton33.setText("jRadioButton1");

        jRadioButton47.setText("jRadioButton1");

        jRadioButton61.setText("jRadioButton1");

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRB20.setText("jRadioButton1");

        jRB31.setText("jRadioButton1");

        jRB27.setText("jRadioButton1");

        jRB25.setText("jRadioButton1");

        jRB9.setText("jRadioButton1");

        jRB39.setText("jRadioButton1");

        jRB23.setText("jRadioButton1");

        jRB21.setText("jRadioButton1");

        jRB5.setText("jRadioButton1");

        jRB40.setText("jRadioButton1");

        jRB19.setText("jRadioButton1");

        jRB16.setText("jRadioButton1");

        jRB37.setText("jRadioButton1");

        jRB38.setText("jRadioButton1");

        jRB6.setText("jRadioButton1");

        jRB15.setText("jRadioButton1");

        jRB18.setText("jRadioButton1");

        jRB8.setText("jRadioButton1");
        jRB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB8ActionPerformed(evt);
            }
        });

        jRB36.setText("jRadioButton1");

        jRB32.setText("jRadioButton1");

        jRB22.setText("jRadioButton1");

        jRB26.setText("jRadioButton1");

        jRB28.setText("jRadioButton1");

        jRB13.setText("jRadioButton1");

        jRB35.setText("jRadioButton1");

        jRB17.setText("jRadioButton1");

        jRB29.setText("jRadioButton1");

        jRB3.setText("jRadioButton1");

        jRB4.setText("jRadioButton1");
        jRB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB4ActionPerformed(evt);
            }
        });

        jRB1.setText("jRadioButton1");

        jRB33.setText("jRadioButton1");

        jRB2.setText("jRadioButton1");

        jRB34.setText("jRadioButton1");

        jRB30.setText("jRadioButton1");

        jRB7.setText("jRadioButton1");

        jRB10.setText("jRadioButton1");

        jRB14.setText("jRadioButton1");

        jRB12.setText("jRadioButton1");

        jRB11.setText("jRadioButton1");

        jRB24.setText("jRadioButton1");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pantalla");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRB41.setBackground(new java.awt.Color(153, 204, 255));
        jRB41.setForeground(new java.awt.Color(0, 0, 255));
        jRB41.setText("jRadioButton1");
        jRB41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB41ActionPerformed(evt);
            }
        });

        jRB42.setBackground(new java.awt.Color(153, 204, 255));
        jRB42.setForeground(new java.awt.Color(0, 0, 204));
        jRB42.setText("jRadioButton1");

        jRB43.setBackground(new java.awt.Color(153, 204, 255));
        jRB43.setText("jRadioButton1");

        jRB44.setBackground(new java.awt.Color(153, 204, 255));
        jRB44.setText("jRadioButton1");
        jRB44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB44ActionPerformed(evt);
            }
        });

        jRB45.setBackground(new java.awt.Color(153, 204, 255));
        jRB45.setText("jRadioButton1");

        jRB46.setBackground(new java.awt.Color(153, 204, 255));
        jRB46.setText("jRadioButton1");

        jRB47.setBackground(new java.awt.Color(153, 204, 255));
        jRB47.setText("jRadioButton1");

        jRB48.setBackground(new java.awt.Color(153, 204, 255));
        jRB48.setText("jRadioButton1");
        jRB48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB48ActionPerformed(evt);
            }
        });

        jRB49.setBackground(new java.awt.Color(153, 204, 255));
        jRB49.setText("jRadioButton1");

        jRB50.setBackground(new java.awt.Color(153, 204, 255));
        jRB50.setText("jRadioButton1");

        jRB51.setBackground(new java.awt.Color(153, 204, 255));
        jRB51.setText("jRadioButton1");

        jRB52.setBackground(new java.awt.Color(153, 204, 255));
        jRB52.setText("jRadioButton1");

        jRB53.setBackground(new java.awt.Color(153, 204, 255));
        jRB53.setText("jRadioButton1");
        jRB53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB53ActionPerformed(evt);
            }
        });

        jRB54.setBackground(new java.awt.Color(153, 204, 255));
        jRB54.setText("jRadioButton1");

        jRB55.setBackground(new java.awt.Color(153, 204, 255));
        jRB55.setText("jRadioButton1");

        jRB56.setBackground(new java.awt.Color(153, 204, 255));
        jRB56.setText("jRadioButton1");

        jRB57.setBackground(new java.awt.Color(153, 204, 255));
        jRB57.setText("jRadioButton1");

        jRB58.setBackground(new java.awt.Color(153, 204, 255));
        jRB58.setText("jRadioButton1");

        jRB59.setBackground(new java.awt.Color(153, 204, 255));
        jRB59.setText("jRadioButton1");

        jRB60.setBackground(new java.awt.Color(153, 204, 255));
        jRB60.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jRB41, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRB50, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB51, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRB42, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB43, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB44, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB45, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB46, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB47, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB48, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB49, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRB52, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB53, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB54, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB55, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB56, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB57, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB58, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB59, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB60, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB41)
                    .addComponent(jRB42)
                    .addComponent(jRB43)
                    .addComponent(jRB44)
                    .addComponent(jRB45)
                    .addComponent(jRB46)
                    .addComponent(jRB47)
                    .addComponent(jRB48)
                    .addComponent(jRB49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB50)
                    .addComponent(jRB51)
                    .addComponent(jRB52)
                    .addComponent(jRB53)
                    .addComponent(jRB54)
                    .addComponent(jRB55)
                    .addComponent(jRB56)
                    .addComponent(jRB57)
                    .addComponent(jRB58)
                    .addComponent(jRB59)
                    .addComponent(jRB60))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRB3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRB29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRB2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRB4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRB30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jRB7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRB6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRB17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRB31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB33, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB35, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRB22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRB36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRB25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRB37, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB38, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB39, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB40, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB5)
                    .addComponent(jRB6)
                    .addComponent(jRB7)
                    .addComponent(jRB8)
                    .addComponent(jRB9)
                    .addComponent(jRB10)
                    .addComponent(jRB11)
                    .addComponent(jRB12)
                    .addComponent(jRB13)
                    .addComponent(jRB14)
                    .addComponent(jRB15)
                    .addComponent(jRB16)
                    .addComponent(jRB1)
                    .addComponent(jRB2))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB17)
                    .addComponent(jRB18)
                    .addComponent(jRB19)
                    .addComponent(jRB20)
                    .addComponent(jRB21)
                    .addComponent(jRB22)
                    .addComponent(jRB25)
                    .addComponent(jRB26)
                    .addComponent(jRB27)
                    .addComponent(jRB23)
                    .addComponent(jRB28)
                    .addComponent(jRB24)
                    .addComponent(jRB4)
                    .addComponent(jRB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB29)
                    .addComponent(jRB30)
                    .addComponent(jRB31)
                    .addComponent(jRB32)
                    .addComponent(jRB33)
                    .addComponent(jRB34)
                    .addComponent(jRB36)
                    .addComponent(jRB37)
                    .addComponent(jRB38)
                    .addComponent(jRB39)
                    .addComponent(jRB40)
                    .addComponent(jRB35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRB53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB53ActionPerformed

    private void jRB48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB48ActionPerformed

    private void jRB44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB44ActionPerformed

    private void jRB41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB41ActionPerformed

    private void jRB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB4ActionPerformed

    private void jRB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRB1;
    private javax.swing.JRadioButton jRB10;
    private javax.swing.JRadioButton jRB11;
    private javax.swing.JRadioButton jRB12;
    private javax.swing.JRadioButton jRB13;
    private javax.swing.JRadioButton jRB14;
    private javax.swing.JRadioButton jRB15;
    private javax.swing.JRadioButton jRB16;
    private javax.swing.JRadioButton jRB17;
    private javax.swing.JRadioButton jRB18;
    private javax.swing.JRadioButton jRB19;
    private javax.swing.JRadioButton jRB2;
    private javax.swing.JRadioButton jRB20;
    private javax.swing.JRadioButton jRB21;
    private javax.swing.JRadioButton jRB22;
    private javax.swing.JRadioButton jRB23;
    private javax.swing.JRadioButton jRB24;
    private javax.swing.JRadioButton jRB25;
    private javax.swing.JRadioButton jRB26;
    private javax.swing.JRadioButton jRB27;
    private javax.swing.JRadioButton jRB28;
    private javax.swing.JRadioButton jRB29;
    private javax.swing.JRadioButton jRB3;
    private javax.swing.JRadioButton jRB30;
    private javax.swing.JRadioButton jRB31;
    private javax.swing.JRadioButton jRB32;
    private javax.swing.JRadioButton jRB33;
    private javax.swing.JRadioButton jRB34;
    private javax.swing.JRadioButton jRB35;
    private javax.swing.JRadioButton jRB36;
    private javax.swing.JRadioButton jRB37;
    private javax.swing.JRadioButton jRB38;
    private javax.swing.JRadioButton jRB39;
    private javax.swing.JRadioButton jRB4;
    private javax.swing.JRadioButton jRB40;
    private javax.swing.JRadioButton jRB41;
    private javax.swing.JRadioButton jRB42;
    private javax.swing.JRadioButton jRB43;
    private javax.swing.JRadioButton jRB44;
    private javax.swing.JRadioButton jRB45;
    private javax.swing.JRadioButton jRB46;
    private javax.swing.JRadioButton jRB47;
    private javax.swing.JRadioButton jRB48;
    private javax.swing.JRadioButton jRB49;
    private javax.swing.JRadioButton jRB5;
    private javax.swing.JRadioButton jRB50;
    private javax.swing.JRadioButton jRB51;
    private javax.swing.JRadioButton jRB52;
    private javax.swing.JRadioButton jRB53;
    private javax.swing.JRadioButton jRB54;
    private javax.swing.JRadioButton jRB55;
    private javax.swing.JRadioButton jRB56;
    private javax.swing.JRadioButton jRB57;
    private javax.swing.JRadioButton jRB58;
    private javax.swing.JRadioButton jRB59;
    private javax.swing.JRadioButton jRB6;
    private javax.swing.JRadioButton jRB60;
    private javax.swing.JRadioButton jRB7;
    private javax.swing.JRadioButton jRB8;
    private javax.swing.JRadioButton jRB9;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton61;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
