/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.udistrital.cine.presentacion;

/**
 *
 * @author USER
 */
public class VistaMain extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public VistaMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        jbPelicula1 = new javax.swing.JButton();
        jbPelicula3 = new javax.swing.JButton();
        jbPelicula4 = new javax.swing.JButton();
        jbPelicula5 = new javax.swing.JButton();
        jbPelicula6 = new javax.swing.JButton();
        jlTittle = new javax.swing.JLabel();
        jbPelicula2 = new javax.swing.JButton();
        jlPortada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpMain.setLayout(null);

        jbPelicula1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbPelicula1.setText("Pelicula 1");
        jpMain.add(jbPelicula1);
        jbPelicula1.setBounds(60, 110, 120, 80);

        jbPelicula3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbPelicula3.setText("Pelicula 3");
        jpMain.add(jbPelicula3);
        jbPelicula3.setBounds(500, 110, 150, 80);

        jbPelicula4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbPelicula4.setText("Pelicula 4");
        jpMain.add(jbPelicula4);
        jbPelicula4.setBounds(60, 300, 160, 80);

        jbPelicula5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbPelicula5.setText("Pelicula 5");
        jpMain.add(jbPelicula5);
        jbPelicula5.setBounds(290, 300, 130, 80);

        jbPelicula6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbPelicula6.setText("Pelicula 6");
        jpMain.add(jbPelicula6);
        jbPelicula6.setBounds(500, 300, 150, 80);

        jlTittle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jlTittle.setForeground(new java.awt.Color(255, 255, 255));
        jlTittle.setText("CINE JUNGLA");
        jpMain.add(jlTittle);
        jlTittle.setBounds(30, 20, 320, 60);

        jbPelicula2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbPelicula2.setText("Pelicula 2");
        jpMain.add(jbPelicula2);
        jbPelicula2.setBounds(290, 110, 130, 80);

        jlPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UD/cine/Jungla.jpg"))); // NOI18N
        jlPortada.setText("CINE JUNGLA");
        jpMain.add(jlPortada);
        jlPortada.setBounds(11, 10, 690, 497);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbPelicula1;
    private javax.swing.JButton jbPelicula2;
    private javax.swing.JButton jbPelicula3;
    private javax.swing.JButton jbPelicula4;
    private javax.swing.JButton jbPelicula5;
    private javax.swing.JButton jbPelicula6;
    private javax.swing.JLabel jlPortada;
    private javax.swing.JLabel jlTittle;
    private javax.swing.JPanel jpMain;
    // End of variables declaration//GEN-END:variables
}
